- hosts: all
  user: root
  tasks:
  - name: Stop Nginx
    service:
      name: nginx
      state: stopped
  - name: Restart the firewalld service to load in the firewall changes
    service:
      name: firewalld
      state: stopped
  - name: Open port 80 for http access
    firewalld:
      service: http
      permanent: true
      state: disabled
  - name: Check if file already exists
    stat:
      path: /usr/share/nginx/html/index.html
    register: file_exists
  - name: Delete the file if it exists
    file:
      path: /usr/share/nginx/html/index.html
      state: absent
    when: file_exists.stat.exists
  - name: un-install Nginx
    yum:
      name: nginx
      state: absent
  - name: remove epel-repo
    yum:
      name: epel-release
      state: absent
